// Package init Code generated by "router-annotation";DO NOT EDIT.
package initialize

import (
	"github.com/gin-gonic/gin"
	"ocpp-client/api"
	"ocpp-client/api/group"
)

var engine *gin.Engine

func init() {
	engine = gin.Default()

	transactionGroup := engine.Group(group.Transaction)
	{
		// TransactionEvent 充电
		transactionGroup.POST("/add", api.TransactionEvent)
	}

	chargeStationGroup := engine.Group(group.ChargeStation)
	{
		// ListChargeStation 充电桩列表
		chargeStationGroup.POST("/list", api.ListChargeStation)
		// NewChargeStation 创建充电桩
		chargeStationGroup.POST("/add", api.NewChargeStation)
		// Command 发送充电桩命令
		chargeStationGroup.POST("/command", api.Command)
	}

}
func GinEngine() *gin.Engine {
	return engine
}
